### ISSUE TITLE
allow variables in config patches

### ISSUE THREAD

**Issue by smira** [talos-systems/cluster-api-bootstrap-provider-talos#96]
e.g. we could have used machine name as machine's hostname

alternatively, this could be just a feature enabled in the spec

**Comment by dimatha** [comment]
That would be perfect! 

If I understand it right, there is no way as of now to get the machine name from CAPI and set it on the Talos node(s)?

**Comment by smira** [comment]
well, that depends on the infrastructure provider in general - e.g. on AWS VM name will match Machine name, but hostname will be different (driven by AWS cloud controller logic).

on bare-metal (with Sidero) there's no way to push machine name down to the host.

**Comment by dimatha** [comment]
I'm currently on CAPV (vSphere). Sorry, forgot to mention that one

**Comment by dimatha** [comment]
Not sure if that's following Talos approach but I'll leave it here for a reference. 
CAPI kubeadm bootstrap: https://cluster-api.sigs.k8s.io/tasks/kubeadm-bootstrap.html
Cloud-init config-data is used to deliver the hostname of the Machine and it can be used with a mixture of shell commands to set the hostname, etc.

**Comment by Preisschild** [comment]
Would it make sense to merge this with https://github.com/siderolabs/cluster-api-bootstrap-provider-talos/issues/155 and allow variables to be substituted with Kubernetes secrets as well as other sources?

For example, this configPatch

```yaml
- op: add
  path: /machine/registries/config
  value:
    registry.example.org:
      auth:
        username: testuser
        password: $EXAMPLEREGISTRY_PASS
```

could be substituted with an optional, per-cluster Kubernetes secret that could look like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: <clustername>-talos-vars
type: Opaque
stringData:
  EXAMPLEREGISTRY_PASS: testpassword
```
